title: Shaheer Khan # your name (or website title) here
logo: "/images/Shaheer headshot.jfif?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I help businesses simplify multi-faceted problems, providing an easier understanding of actionable solutions. 
  <br><br>
  My specialties include data analysis, data wrangling, data visualization, and data communication. 
  <br><br>
  <a href="https://www.linkedin.com/in/shaheerkhan200/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
